[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
  from = "https://critically-mia.netlify.app"
  to = "https://ghost.critically-mia.me"
  status = 301
  force = true
